// countries.js — Europäische Länder (ISO 3166-1 alpha-2 + deutscher Name)
// Das country-Feld der DB ist CHAR(2); gespeichert wird der Code.
export const EU_COUNTRIES = [
  { code: 'AL', name: 'Albanien' },
  { code: 'AD', name: 'Andorra' },
  { code: 'BE', name: 'Belgien' },
  { code: 'BA', name: 'Bosnien und Herzegowina' },
  { code: 'BG', name: 'Bulgarien' },
  { code: 'DK', name: 'Dänemark' },
  { code: 'DE', name: 'Deutschland' },
  { code: 'EE', name: 'Estland' },
  { code: 'FI', name: 'Finnland' },
  { code: 'FR', name: 'Frankreich' },
  { code: 'GR', name: 'Griechenland' },
  { code: 'GB', name: 'Großbritannien' },
  { code: 'IE', name: 'Irland' },
  { code: 'IS', name: 'Island' },
  { code: 'IT', name: 'Italien' },
  { code: 'HR', name: 'Kroatien' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'LV', name: 'Lettland' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Litauen' },
  { code: 'LU', name: 'Luxemburg' },
  { code: 'MT', name: 'Malta' },
  { code: 'MD', name: 'Moldau' },
  { code: 'MC', name: 'Monaco' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'NL', name: 'Niederlande' },
  { code: 'MK', name: 'Nordmazedonien' },
  { code: 'NO', name: 'Norwegen' },
  { code: 'AT', name: 'Österreich' },
  { code: 'PL', name: 'Polen' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Rumänien' },
  { code: 'RU', name: 'Russland' },
  { code: 'SM', name: 'San Marino' },
  { code: 'SE', name: 'Schweden' },
  { code: 'CH', name: 'Schweiz' },
  { code: 'RS', name: 'Serbien' },
  { code: 'SK', name: 'Slowakei' },
  { code: 'SI', name: 'Slowenien' },
  { code: 'ES', name: 'Spanien' },
  { code: 'CZ', name: 'Tschechien' },
  { code: 'TR', name: 'Türkei' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'HU', name: 'Ungarn' },
  { code: 'BY', name: 'Belarus' },
  { code: 'VA', name: 'Vatikanstadt' },
  { code: 'CY', name: 'Zypern' },
];
