// Beispieldaten — werden durch API-Calls ersetzt

export const CL_CAVES = [
  {
    id: 'hermannshoehle',
    name: 'Hermannshöhle',
    region: 'Harz, Niedersachsen',
    country: 'DE',
    depth: 45,
    length: 2100,
    type: 'Mixed',
    discovered: 1866,
    lat: 51.7342, lng: 10.5621,
    entries: 12,
  },
  {
    id: 'rieseneishoehle',
    name: 'Rieseneishöhle',
    region: 'Dachstein, Oberösterreich',
    country: 'AT',
    depth: 407,
    length: 4500,
    type: 'Vertikal',
    discovered: 1910,
    lat: 47.5120, lng: 13.6940,
    entries: 8,
  },
  {
    id: 'schwarzmoos',
    name: 'Schwarzmooskogel-Höhlensystem',
    region: 'Totes Gebirge, Steiermark',
    country: 'AT',
    depth: 1291,
    length: 138000,
    type: 'Vertikal',
    discovered: 1982,
    lat: 47.7280, lng: 13.8140,
    entries: 3,
  },
  {
    id: 'falkensteiner',
    name: 'Falkensteiner Höhle',
    region: 'Schwäbische Alb, BW',
    country: 'DE',
    depth: 25,
    length: 4200,
    type: 'Horizontal',
    discovered: 1823,
    lat: 48.4850, lng: 9.5530,
    entries: 15,
  },
  {
    id: 'barenhoehle',
    name: 'Bärenhöhle bei Sonnenbühl',
    region: 'Schwäbische Alb, BW',
    country: 'DE',
    depth: 12,
    length: 271,
    type: 'Horizontal',
    discovered: 1834,
    lat: 48.3980, lng: 9.2250,
    entries: 4,
  },
  {
    id: 'holloch',
    name: 'Hölloch',
    region: 'Muotathal, Schwyz',
    country: 'CH',
    depth: 939,
    length: 205000,
    type: 'Labyrinth',
    discovered: 1875,
    lat: 46.9833, lng: 8.8500,
    entries: 2,
  },
];

export const CL_TRIPS = [
  {
    id: 't-2026-04-11',
    caveId: 'schwarzmoos',
    title: 'Schacht P38 bis -310m',
    date: '2026-04-11',
    start: '08:30',
    end: '19:45',
    duration: 675,
    type: 'Vertikal',
    wet: 'Teilweise',
    rope: 'SRT',
    difficulty: { t: 5, k: 4, p: 3 },
    rating: 5,
    depth: 310,
    length: 820,
    weather: 'Schneefall, -4°C Eingang',
    team: ['Marco K.', 'Lena R.', 'Tobi F.'],
    gear: ['SRT-Set', 'Neopren 5mm', 'Schlafsack', 'Helm+2xLampe'],
    hazards: ['Steinschlag am P38', 'Schmelzwasser-Zulauf'],
    notes: 'Abstieg durch den Haupteinstieg. P38 war mit Wassereintrag, Stau am Knoten. Biwak auf -280m in der großen Halle. Früh am nächsten Tag Rückzug wegen ansteigendem Wasser.',
    photos: 12,
    heroIcon: 'pit',
  },
  {
    id: 't-2026-03-22',
    caveId: 'falkensteiner',
    title: 'Durchgang bis zum 2. Siphon',
    date: '2026-03-22',
    start: '10:00',
    end: '15:30',
    duration: 330,
    type: 'Horizontal',
    wet: 'Nass',
    rope: 'Ohne',
    difficulty: { t: 2, k: 3, p: 2 },
    rating: 4,
    depth: 25,
    length: 1800,
    weather: 'Trocken, 8°C',
    team: ['Lena R.'],
    gear: ['Neopren 5mm', 'Packsack', 'Helm+Lampe'],
    hazards: ['Niedriger Wasserstand, aber rutschig'],
    notes: 'Vom Eingang bis zum 2. Siphon. Wasserstand ungewöhnlich niedrig, fast komplett trocken bis zum ersten Siphon. Schöne Tropfsteinformation am "Roten Saal".',
    photos: 24,
    heroIcon: 'tunnel',
  },
  {
    id: 't-2026-03-08',
    caveId: 'barenhoehle',
    title: 'Schauhöhlen-Rundgang + Forschungsteil',
    date: '2026-03-08',
    start: '13:15',
    end: '16:00',
    duration: 165,
    type: 'Horizontal',
    wet: 'Trocken',
    rope: 'Ohne',
    difficulty: { t: 1, k: 1, p: 1 },
    rating: 3,
    depth: 12,
    length: 340,
    weather: 'Regen, 4°C',
    team: ['Marco K.', 'Ilse B.', 'Tobi F.'],
    gear: ['Helm+Lampe', 'Overall'],
    hazards: [],
    notes: 'Entspannte Tour mit Gästen. Der abgesperrte Forschungsteil hinter der Höhlenbären-Vitrine wurde mit Führung vom örtlichen Höhlenverein begangen.',
    photos: 18,
    heroIcon: 'chamber',
  },
  {
    id: 't-2026-02-14',
    caveId: 'holloch',
    title: 'Silvretta-Galerie Biwak',
    date: '2026-02-14',
    start: '07:00',
    end: '23:30',
    duration: 990,
    type: 'Labyrinth',
    wet: 'Teilweise',
    rope: 'Mit Seil',
    difficulty: { t: 3, k: 5, p: 4 },
    rating: 5,
    depth: 480,
    length: 6200,
    weather: 'Klar, -8°C',
    team: ['Marco K.', 'Lena R.', 'Tobi F.', 'Anna S.'],
    gear: ['SRT-Set', 'Biwak-Zelt', 'Kocher', 'Neopren 3mm'],
    hazards: ['Orientierung im Labyrinth', 'CO₂ im Winterzweig'],
    notes: '16 Stunden Tour mit Biwak-Pause. Der Winterzweig zeigte leicht erhöhte CO₂-Werte, aber unter 2%. Vermessung von 140m Neuland in der Silvretta-Galerie.',
    photos: 31,
    heroIcon: 'maze',
  },
  {
    id: 't-2026-01-28',
    caveId: 'hermannshoehle',
    title: 'Winterbefahrung Nordteil',
    date: '2026-01-28',
    start: '09:30',
    end: '14:15',
    duration: 285,
    type: 'Mixed',
    wet: 'Trocken',
    rope: 'Mit Seil',
    difficulty: { t: 2, k: 2, p: 2 },
    rating: 4,
    depth: 38,
    length: 1100,
    weather: 'Schnee, -6°C',
    team: ['Marco K.', 'Lena R.'],
    gear: ['Abseilachter', 'Helm+Lampe', 'Overall'],
    hazards: ['Vereister Eingang'],
    notes: 'Eingangsbereich vereist, mit Steigeisen gequert. Innen angenehme 8°C. Der neu erforschte Nordteil bis zum Lehmsiphon.',
    photos: 9,
    heroIcon: 'ice',
  },
  {
    id: 't-2025-11-05',
    caveId: 'rieseneishoehle',
    title: 'Eisdom-Fotoexpedition',
    date: '2025-11-05',
    start: '06:45',
    end: '17:20',
    duration: 635,
    type: 'Vertikal',
    wet: 'Trocken',
    rope: 'SRT',
    difficulty: { t: 4, k: 4, p: 3 },
    rating: 5,
    depth: 220,
    length: 950,
    weather: 'Sonnig, -2°C',
    team: ['Lena R.', 'Anna S.'],
    gear: ['SRT-Set', 'Fotoausrüstung', 'Blitze x3'],
    hazards: ['Rutschige Eistreppen'],
    notes: 'Fotosession für den neuen Bildband. Licht-Setup im Eisdom mit 3 entfernten Blitzen. Temperatur konstant -1°C, Kamera-Akkus unter der Jacke gehalten.',
    photos: 47,
    heroIcon: 'ice',
  },
];

export const CL_CURRENT_USER = {
  name: 'Marco Kellner',
  handle: '@marco',
  role: 'admin',
  since: '2019-06',
  trips: CL_TRIPS.length,
  caves: new Set(CL_TRIPS.map(t => t.caveId)).size,
  totalDepth: CL_TRIPS.reduce((s, t) => s + t.depth, 0),
  totalLength: CL_TRIPS.reduce((s, t) => s + t.length, 0),
  totalHours: Math.round(CL_TRIPS.reduce((s, t) => s + t.duration, 0) / 60),
};

export function getCave(id) {
  return CL_CAVES.find(c => c.id === id);
}
